# Server configuration
server:
  port: 8080

# Spring configuration
spring:
  application:
    name: Price Scheduler API

  # H2 in-memory database configuration
  # Using PostgreSQL compatibility mode for better SQL standard compliance
  datasource:
    url: jdbc:h2:mem:price-scheduler-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: admin
    password:

  # SQL initialization configuration
  # We use explicit SQL scripts instead of JPA auto-DDL for better control and portability
  sql:
    init:
      mode: always                          # Always execute initialization scripts on startup
      schema-locations: classpath:schema.sql # DDL script to create table structure
      data-locations: classpath:data.sql     # DML script to load initial test data from exercise

  # H2 console for database inspection during development
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA/Hibernate configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # ddl-auto: none - We disable Hibernate auto-DDL generation
      # Reason: We want explicit control over schema via schema.sql for:
      #   1. Better version control of database structure
      #   2. Explicit indexes and constraints definition
      #   3. Production-like environment simulation
      #   4. Easier migration to real databases
      ddl-auto: none
    show-sql: true                          # Log SQL statements for debugging
    properties:
      hibernate:
        format_sql: true                    # Pretty-print SQL in logs
        use_sql_comments: true              # Add contextual comments to SQL
    # defer-datasource-initialization: true
    # Critical: Ensures schema.sql and data.sql run BEFORE Hibernate validates entity mappings
    # Without this, Hibernate would fail trying to validate entities against non-existent tables
    defer-datasource-initialization: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"